In [29]:
import pandas as pd
import numpy as np

data = ([
    [1,2,3,4],
    [5,4,3,4],
    [2,3,4,5],
    [3,1,2,5],
    [2,1,5,7],
])
df = pd.DataFrame(data, columns= (['A','B','C','D']))
print (df)

   A  B  C  D
0  1  2  3  4
1  5  4  3  4
2  2  3  4  5
3  3  1  2  5
4  2  1  5  7

In [30]:
pd.DataFrame(df)

   A  B  C  D
0  1  2  3  4
1  5  4  3  4
2  2  3  4  5
3  3  1  2  5
4  2  1  5  7

In [21]:
df.head(2)

   0  1  2  3
0  1  2  3  4
1  5  4  3  4

In [31]:
df.head(3)

   A  B  C  D
0  1  2  3  4
1  5  4  3  4
2  2  3  4  5

In [32]:
df.tail(2)

   A  B  C  D
3  3  1  2  5
4  2  1  5  7

In [33]:
df.tail(3)

   A  B  C  D
2  2  3  4  5
3  3  1  2  5
4  2  1  5  7

In [34]:
df.iloc[0]

A    1
B    2
C    3
D    4
Name: 0, dtype: int64

In [35]:
df.iloc[3]

A    3
B    1
C    2
D    5
Name: 3, dtype: int64

In [41]:
df.iloc[0:5]

   A  B  C  D
0  1  2  3  4
1  5  4  3  4
2  2  3  4  5
3  3  1  2  5
4  2  1  5  7

In [40]:
df.iloc[0:3]

   A  B  C  D
0  1  2  3  4
1  5  4  3  4
2  2  3  4  5

In [45]:
df['A']

0    1
1    5
2    2
3    3
4    2
Name: A, dtype: int64

In [56]:
df.iloc[0:4, 0:2]

   A  B
0  1  2
1  5  4
2  2  3
3  3  1

In [58]:
arr = np.array([[3,1,5],[1,3,2],[4,2,6],[2,5,1]])
np.sort(arr)

array([[1, 3, 5],
       [1, 2, 3],
       [2, 4, 6],
       [1, 2, 5]])

In [66]:
print(np.sort(arr,axis=0))

[[1 1 1]
 [2 2 2]
 [3 3 5]
 [4 5 6]]

In [68]:
print(np.sort(arr,axis=1))

[[1 1 1]
 [2 2 2]
 [3 3 5]
 [4 5 6]]